# -*- coding: utf-8 -*-
"""ReverseDictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbjrewJQ1T0UiEU8BS0uGXQLQewxq7QM
"""

import requests
import json

print("="*40)
print("REVERSE DICTIONARY")
print("I will guess the words based on your description!")
print("="*40)
while True:

    user = input('Describe anything you want:')

    if user == 'quit':
      print('byebye')
      break


    response = requests.get (
        "https://api.datamuse.com/words",
        params={"ml": user, "max": 5}  # ml = means like
    )


    data = response.json()

    #print the response

    for pair in enumerate(data,1):
      #print(pair)
      i = pair[0]
      words = pair[1]
      word = words['word'] #accessing dictionary

      print(f"related words are: {i}.{word}")

